# Generated by Django 4.1.1 on 2022-09-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_content_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='responding_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.comment'),
        ),
    ]
